const AppError = require('../helpers/appError.helper');
const catchAsync = require('../helpers/catchAsync.helper');

exports.createNewVoucher = catchAsync(async (req, res, next) => {

});